seed: 123
num_gpus: 1
num_epochs: 5
resume_dir: /Users/dimafadeev/Desktop/Catalog/TUM/WS23/ML3D/repo/output/models/
print_interval: 10


solver:
  method: adam
  lr: 0.0001
  weight_decay: 0.00001

dataset:
  root_dir: /Users/dimafadeev/Desktop/Catalog/TUM/WS23/ML3D/repo/output/processed/
  batch_size: 16
  num_workers: 8

model:
  arch: resnet101 #  dpt #  
  pretrained: True
  embed_dims: 2
  fix_bn: False
  semantic: True
